swagger: "2.0"
info:
  version: "1.0.0"
  title: Minimal Logic App API
host: prod-05.norwaywest.logic.azure.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /invoke:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        "200":
          description: OK
