openapi: 3.0.1
info:
  title: Logic App HTTP Trigger
  version: 1.0.0
servers:
  - url: https://prod-05.norwaywest.logic.azure.com/workflows/f59e752e0bef4eb8a3131ea8051fc8af/triggers/When_an_HTTP_request_is_received
paths:
  /paths/invoke:
    post:
      operationId: invokeLogicApp
      summary: Kall Logic App
      parameters:
        - in: query
          name: api-version
          required: true
          schema: { type: string }
          example: "2016-10-01"
        - in: query
          name: sp
          required: true
          schema: { type: string }
          example: "/triggers/When_an_HTTP_request_is_received/run"
        - in: query
          name: sv
          required: true
          schema: { type: string }
          example: "1.0"
        - in: query
          name: sig
          required: true
          schema: { type: string }
          description: Shared access signature key
      requestBody:
        required: true
        description: Mottakerpayload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipientPayload'
        x-bodyName: body   # many tools understand this; harmless if ignored
      responses:
        "200":
          description: Forespørselen ble utført uten feil
          content:
            application/json:
              schema: { type: object }
components:
  schemas:
    RecipientPayload:
      type: object
      properties:
        recipient:
          type: object
          properties:
            Id:        { type: string, description: "Fødselsnummer eller orgnr" }
            IdType:    { type: string, description: "person | organization" }
            FirstName: { type: string }
            LastName:  { type: string }
            Address:   { type: string }
            Address2:  { type: string }
            Zipcode:   { type: string }
            City:      { type: string }
            Country:   { type: string }
            Mail:      { type: string }
            Mobile:    { type: string }
      required: [recipient]
